### ISSUE TITLE
Praser breakes on javascript types

### ISSUE THREAD

**Issue by MrBartusek** [RyanMarcus/dirty-json#28]
Passing this intro dirty-json:
```
{
        type: String,
        value: 'something'
}
```
results in:
```
Error: Found } that I can't handle at line 0:45
    at reduce (C:\Users\MrBartusek\Documents\Development\docs\node_modules\dirty-json\parser.js:517:15)
    at Object.parse (C:\Users\MrBartusek\Documents\Development\docs\node_modules\dirty-json\parser.js:99:16)
    at Object.parse (C:\Users\MrBartusek\Documents\Development\docs\node_modules\dirty-json\dirty-json.js:39:23)
    at praseFileContent (C:\Users\MrBartusek\Documents\Development\docs\scripts\updateConfig.js:32:19)
    at Object.<anonymous> (C:\Users\MrBartusek\Documents\Development\docs\scripts\updateConfig.js:15:21)
```
- As you can see there is no `0:45`
- Sometimes is got line `undefined:undefined` hoverer I cannot reproduce it
- This happens only when a value is written after value with type

**Comment by RyanMarcus** [comment]
This should now be fixed! Thanks for reporting the issue. :)
